version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "9000:9000"
    environment:
      REDIS_DNS: redis

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    environment:
      BACKEND_DNS: backend
      BACKEND_PORT: 9000

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
