name: Main workflow
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  docker_username: piped17
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Go application
        run: go build -v ./...

      - name: Run unit tests
        run: go test -v ./...

      - uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
          include-hidden-files: true

  Linting:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run linting
        run: golangci-lint run ./...

  Docker-image:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions: 
      packages: write
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .

      - name: Build Docker image
        run: bash ci/build-docker.sh

      - name: Push Docker image
        run: bash ci/push-docker.sh
