name: Main workflow
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  docker_username: piped17
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        working-directory: ./backend
        run: go build -v ./...

      - name: Build
        working-directory: ./frontend
        run: go build -v ./...

      - name: Test
        working-directory: ./frontend
        run: go test -v ./...

      - name: Test
        working-directory: ./backend
        run: go test -v ./...

      - name: Upload code artifact
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
          include-hidden-files: true


