name: Main workflow
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  docker_username: piped17
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
  GIT_COMMIT: ${{ github.sha }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        working-directory: ./backend
        run: go build -v ./...

      - name: Build
        working-directory: ./frontend
        run: go build -v ./...

      - name: Test
        working-directory: ./frontend
        run: go test -v ./...

      - name: Test
        working-directory: ./backend
        run: go test -v ./...

      - name: Upload code artifact
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
          include-hidden-files: true
                   
  Docker-image:
      runs-on: ubuntu-latest
      needs: [Build]
      permissions: 
        packages: write
      steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ env.docker_username }}
            password: ${{ env.docker_password }}
      
        - name: download code
          uses: actions/download-artifact@v4
          with:
              name: code
              path: .
        - name: Build and Push Frontend Docker Image
          run: |
            docker build -t ${{ env.docker_username }}/frontend:latest ./frontend
            docker push ${{ env.docker_username }}/frontend:latest
        - name: Build and Push backend Docker Image
          run: |
            docker build -t ${{ env.docker_username }}/backend:latest ./backend
            docker push ${{ env.docker_username }}/backend:latest

  Deploy:
    runs-on: ubuntu-latest
    needs: [Docker-image]
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v4
      - name: Write kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
      - name: Deploy to Kubernetes
        run:  kubectl --kubeconfig kubeconfig apply -f ./k8s
  
  Test-curl:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build test version with docker up
        run: |
          docker compose up -d
          curl http://localhost:8080/
      - name: Clean up docker build
        run: docker compose down
